"""empty message

Revision ID: 0208f3337967
Revises: 
Create Date: 2020-03-24 14:52:49.960414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0208f3337967'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cities', 'region_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('cities_region_id_fkey', 'cities', type_='foreignkey')
    op.create_foreign_key(None, 'cities', 'regions', ['region_id'], ['parent_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cities', type_='foreignkey')
    op.create_foreign_key('cities_region_id_fkey', 'cities', 'regions', ['region_id'], ['parent_id'])
    op.alter_column('cities', 'region_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
