"""empty message

Revision ID: 23e399c41544
Revises: 0208f3337967
Create Date: 2020-03-24 22:20:55.185351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23e399c41544'
down_revision = '0208f3337967'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'cities', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cities', type_='unique')
    # ### end Alembic commands ###
