"""empty message

Revision ID: 958cfc9b1a6d
Revises: 23e399c41544
Create Date: 2020-03-25 00:31:46.616084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '958cfc9b1a6d'
down_revision = '23e399c41544'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('login'),
    sa.UniqueConstraint('password')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
